export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const LOCATION_ERROR_MESSAGE = 'LOCATION_ERROR_MESSAGE';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';
export const GET_FORECAST_ERROR = 'GET_FORECAST_ERROR';
export const SEARCH_ERROR = 'SEARCH_ERROR';