export const GET_CURRENTLOCALWEATHER_SUCCESS = 'GET_CURRENTLOCALWEATHER_SUCCESS';
export const GET_LOCALFORECAST_SUCCESS = 'GET_LOCALFORECAST_SUCCESS';
export const LOCATION_ERROR_MESSAGE = 'LOCATION_ERROR_MESSAGE';
export const WEATHER_ERROR_MESSAGE = 'WEATHER_ERROR_MESSAGE';
export const FORECAST_ERROR_MESSAGE = 'FORECAST_ERROR_MESSAGE';